const express = require('express');
const router = express.Router();
const reservationController = require('../controllers/reservationController');
const reservationCreateController = require('../controllers/reservationCreateController');
const reservationMutationController = require('../controllers/reservationMutationController');
const reservationLifecycleController = require('../controllers/reservationLifecycleController');
const reservationApprovalController = require('../controllers/reservationApprovalController');
const scopedQueryController = require('../controllers/scopedQueryController');
const checkinCredentialController = require('../controllers/checkinCredentialController');
const { auth, requireAdmin } = require('../middleware/auth');
const adminScope = require('../middleware/adminScope');
const optionalAdminScope = require('../middleware/optionalAdminScope');
const optionalAdminReservationScope = require('../middleware/optionalAdminReservationScope');
const { createReservationRules, reservationIdRules, waitlistRules, paginationRules, auditRules } = require('../middleware/validator');
const { reservationLimiter } = require('../middleware/rateLimit');

router.post('/', auth, reservationLimiter, createReservationRules, reservationCreateController.create);
router.get('/', auth, optionalAdminScope, paginationRules, reservationController.list);
router.get('/pending', auth, requireAdmin, adminScope.loadAdminScope, scopedQueryController.pendingReservations);
router.get('/pending-count', auth, requireAdmin, adminScope.loadAdminScope, scopedQueryController.pendingReservationCount);
router.put('/:id/approve', auth, requireAdmin, adminScope.loadAdminScope, adminScope.reservationFromParam('id'), auditRules, reservationApprovalController.approve);
router.put('/:id/reject', auth, requireAdmin, adminScope.loadAdminScope, adminScope.reservationFromParam('id'), auditRules, reservationApprovalController.reject);
router.get('/:id', auth, optionalAdminReservationScope('id'), reservationIdRules, reservationController.detail);
router.delete('/:id', auth, optionalAdminReservationScope('id'), reservationIdRules, reservationLifecycleController.cancel);
router.put('/:id', auth, optionalAdminReservationScope('id'), reservationIdRules, reservationMutationController.update);
router.get('/:id/qrcode', auth, optionalAdminReservationScope('id'), reservationIdRules, checkinCredentialController.issue);
router.post('/:id/rebook', auth, optionalAdminReservationScope('id'), reservationIdRules, reservationMutationController.rebook);
router.post('/check-conflict', auth, reservationController.checkConflict);
router.post('/waitlist', auth, reservationLimiter, waitlistRules, reservationController.joinWaitlist);
router.delete('/:id/waitlist', auth, reservationIdRules, reservationController.leaveWaitlist);

module.exports = router;
