const router = require('express').Router();
const { auth, requireRole } = require('../middleware/auth');
const scope = require('../middleware/adminScope');
const c = require('../controllers/verificationController');
const rateLimit = require('express-rate-limit');
const scanLimiter = rateLimit({ windowMs: 60000, max: 120, keyGenerator: req => 'verification-admin-' + req.user.id, standardHeaders: true, legacyHeaders: false, handler: (req, res) => res.status(429).json({ code: 429, message: '操作过于频繁，请稍后再试' }) });
router.use(auth);
router.get('/credential/:id', requireRole('student'), c.credential);
router.get('/status/:id', (req, res, next) => req.user.role === 'student' ? next() : scope.loadAdminScope(req, res, next), c.status);
router.use(requireRole('dorm_manager', 'admin', 'counselor', 'super_admin'), scope.loadAdminScope);
router.get('/me', c.me);
router.post('/preview', scanLimiter, c.preview);
router.post('/confirm', scanLimiter, c.confirm);
router.post('/failure', scanLimiter, c.failure);
router.get('/records', c.records);
router.get('/reservations', c.reservations);
router.get('/spaces', c.spaces);
router.post('/records/:id/resolve', requireRole('admin', 'counselor', 'super_admin'), c.resolve);
module.exports = router;
