var request = require('../../utils/request')

function createEmptyForm() { return { id: '', studentNo: '', realName: '', cardNo: '', phone: '', college: '', major: '', grade: '', className: '', buildingId: '', roomNumber: '' } }
function pickUserForm(user) { user = user || {}; return { id: user.id || '', studentNo: user.student_no || user.student_id || '', realName: user.real_name || user.realName || user.name || '', cardNo: user.card_no || user.cardNo || '', phone: user.phone || '', college: user.college || '', major: user.major || '', grade: user.grade || '', className: user.class_name || user.className || '', buildingId: user.building_id || user.buildingId || '', roomNumber: user.room_number || user.roomNumber || '' } }
function importExample() { return '2024001003\t王五\t200003\t13900000003\t敬一书院\t机械工程\t2024级\t1班\t1\tB302\n2024001004\t赵六\t200004\t13900000004\t敬一书院\t智能制造\t2024级\t2班\t1\tB303' }
var buildingOptions = [{ value: '', label: '全部楼栋' }, { value: '1', label: '敬一书院B座' }, { value: '2', label: '敬一书院C座' }, { value: '3', label: '敬一书院D座' }, { value: '4', label: '敬一书院二期一幢' }]
var statusOptions = [{ value: '', label: '全部状态' }, { value: 'active', label: '正常' }, { value: 'banned', label: '封禁' }, { value: 'restricted', label: '限制' }]
function htmlCell(value) { return '<td>' + String(value === undefined || value === null ? '' : value).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;') + '</td>' }
function buildExcelHtml(rows) { return '<html><head><meta charset="utf-8"></head><body><table border="1">' + rows.map(function (row) { return '<tr>' + row.map(htmlCell).join('') + '</tr>' }).join('') + '</table></body></html>' }
function writeAndOpenExcel(filename, rows) { var fs = wx.getFileSystemManager(); var path = wx.env.USER_DATA_PATH + '/' + filename; fs.writeFile({ filePath: path, data: buildExcelHtml(rows), encoding: 'utf8', success: function () { wx.openDocument({ filePath: path, fileType: 'xls', showMenu: true, success: function () { wx.showToast({ title: '已生成Excel文件', icon: 'success' }) }, fail: function () { wx.showToast({ title: '文件已生成，可在聊天中发送', icon: 'none' }) } }) }, fail: function () { wx.showToast({ title: '生成失败', icon: 'none' }) } }) }
function importResultMessage(data) { var msg = '成功' + (data.created || 0) + '条，跳过' + (data.skipped || 0) + '条'; if (data.errors && data.errors.length) msg += '\n' + data.errors.slice(0, 5).join('\n'); return msg }

Page({
  data: { list: [], keyword: '', filteredList: [], showAddForm: false, showImportForm: false, importText: '', importResult: '', formMode: 'create', addForm: createEmptyForm(), submittingAdd: false, submittingImport: false, statusFilter: '', buildingFilter: '', gradeFilter: '', buildingOptions: buildingOptions, statusOptions: statusOptions },
  onLoad: function () { this.loadData() },
  onShow: function () { this.loadData() },
  loadData: function () { var that = this; request.get('/user/list', {}, { silent: true }).then(function (data) { var list = data; if (!Array.isArray(list)) list = data.list || data.users || []; list = that.enhanceUsers(list); that.setData({ list: list, filteredList: that.applyFilter(list) }) }).catch(function () { that.setData({ list: [], filteredList: [] }) }) },
  enhanceUsers: function (list) { return list.map(function (u) { var name = u.name || u.real_name || u.realName || '?'; u.avatarInitial = String(name).charAt(0) || '?'; u.creditDisplay = parseInt(u.credit_score) || 100; return u }) },
  applyFilter: function (list) { var keyword = this.data.keyword; var statusFilter = this.data.statusFilter; var buildingFilter = this.data.buildingFilter; var gradeFilter = this.data.gradeFilter; var kw = String(keyword || '').toLowerCase(); return (list || []).filter(function (u) { if (kw && [u.name, u.real_name, u.realName, u.student_no, u.student_id, u.phone, u.card_no, u.room_number, u.major, u.class_name].join(' ').toLowerCase().indexOf(kw) < 0) return false; if (statusFilter && String(u.status || '') !== String(statusFilter)) return false; if (buildingFilter && String(u.building_id || u.buildingId || '') !== String(buildingFilter)) return false; if (gradeFilter && String(u.grade || '').indexOf(gradeFilter) < 0) return false; return true }) },
  refreshFilter: function () { this.setData({ filteredList: this.applyFilter(this.data.list) }) },
  onSearch: function (e) { this.setData({ keyword: e.detail.value.trim() }); this.refreshFilter() },
  onBuildingFilterChange: function (e) { var option = this.data.buildingOptions[Number(e.detail.value) || 0] || this.data.buildingOptions[0]; this.setData({ buildingFilter: option.value }); this.refreshFilter() },
  onStatusFilterChange: function (e) { var option = this.data.statusOptions[Number(e.detail.value) || 0] || this.data.statusOptions[0]; this.setData({ statusFilter: option.value }); this.refreshFilter() },
  onGradeFilterInput: function (e) { this.setData({ gradeFilter: e.detail.value.trim() }); this.refreshFilter() },
  onClearFilters: function () { this.setData({ keyword: '', statusFilter: '', buildingFilter: '', gradeFilter: '' }); this.refreshFilter() },
  onAddUser: function () { this.setData({ showAddForm: true, formMode: 'create', addForm: createEmptyForm(), submittingAdd: false }) },
  onEditUser: function (e) { var id = e.currentTarget.dataset.id; var user = (this.data.list || []).find(function (item) { return String(item.id) === String(id) }) || {}; this.setData({ showAddForm: true, formMode: 'edit', addForm: pickUserForm(user), submittingAdd: false }) },
  onCancelAdd: function () { if (this.data.submittingAdd) return; this.setData({ showAddForm: false, addForm: createEmptyForm(), formMode: 'create' }) },
  onAddInput: function (e) { var field = e.currentTarget.dataset.field; this.setData({ ['addForm.' + field]: e.detail.value }) },
  validateAddForm: function () { var form = this.data.addForm; if (!String(form.studentNo || '').trim()) return '请输入学号'; if (!/^\d{9,10}$/.test(String(form.studentNo || '').trim())) return '学号应为9-10位数字'; if (!String(form.realName || '').trim()) return '请输入姓名'; if (!String(form.cardNo || '').trim()) return '请输入6位一卡通号'; if (!/^\d{6}$/.test(String(form.cardNo || '').trim())) return '一卡通号应为6位数字'; if (form.phone && !/^1\d{10}$/.test(String(form.phone).trim())) return '手机号格式不正确'; return '' },
  submitAddUser: function () { var that = this; var error = this.validateAddForm(); if (error) { wx.showToast({ title: error, icon: 'none' }); return } if (this.data.submittingAdd) return; var form = Object.assign({}, this.data.addForm); Object.keys(form).forEach(function (key) { form[key] = String(form[key] || '').trim() }); var isEdit = this.data.formMode === 'edit'; var req = isEdit ? request.put('/user/list/' + form.id, form) : request.post('/user/list', form); this.setData({ submittingAdd: true }); req.then(function () { wx.showToast({ title: isEdit ? '宿生已更新' : '宿生已添加', icon: 'success' }); that.setData({ showAddForm: false, addForm: createEmptyForm(), formMode: 'create', submittingAdd: false }); that.loadData() }).catch(function (err) { that.setData({ submittingAdd: false }); wx.showToast({ title: err && err.message ? err.message : '保存失败', icon: 'none' }) }) },
  onOpenImport: function () { this.setData({ showImportForm: true, importText: '', importResult: '', submittingImport: false }) },
  onPasteImportExample: function () { this.setData({ importText: importExample(), importResult: '' }) },
  onImportInput: function (e) { this.setData({ importText: e.detail.value }) },
  onCancelImport: function () { if (this.data.submittingImport) return; this.setData({ showImportForm: false, importText: '', importResult: '' }) },
  onDownloadTemplate: function () { var rows = [['学号', '姓名', '一卡通号', '手机号', '学院', '专业', '年级', '班级', '楼栋ID', '宿舍号'], ['2024001003', '王五', '200003', '13900000003', '敬一书院', '机械工程', '2024级', '1班', '1', 'B302']]; writeAndOpenExcel('宿生导入模板.xls', rows) },
  onChooseImportFile: function () { var that = this; if (this.data.submittingImport) return; wx.chooseMessageFile({ count: 1, type: 'file', extension: ['xlsx', 'xls', 'csv', 'txt'], success: function (res) { var file = res.tempFiles && res.tempFiles[0]; if (!file) return; that.setData({ submittingImport: true, importResult: '正在上传并解析：' + file.name }); request.upload('/user/list/import-file', file.path, 'file', { filename: file.name }, { silent: true }).then(function (data) { that.setData({ submittingImport: false, importResult: importResultMessage(data), importText: '' }); wx.showToast({ title: '文件导入完成', icon: 'success' }); that.loadData() }).catch(function (err) { that.setData({ submittingImport: false, importResult: err && err.message ? err.message : '文件导入失败' }); wx.showToast({ title: err && err.message ? err.message : '文件导入失败', icon: 'none' }) }) } }) },
  onSubmitImport: function () { var that = this; var text = String(this.data.importText || '').trim(); if (!text) { wx.showToast({ title: '请粘贴宿生数据或选择xlsx文件', icon: 'none' }); return } if (this.data.submittingImport) return; this.setData({ submittingImport: true, importResult: '' }); request.post('/user/list/import', { text: text }).then(function (data) { that.setData({ submittingImport: false, importResult: importResultMessage(data) }); wx.showToast({ title: '导入完成', icon: 'success' }); that.loadData() }).catch(function (err) { that.setData({ submittingImport: false }); wx.showToast({ title: err && err.message ? err.message : '导入失败', icon: 'none' }) }) },
  onExportUsers: function () { var rows = [['学号', '姓名', '一卡通号', '手机号', '学院', '专业', '年级', '班级', '楼栋ID', '宿舍号', '信用分', '状态']]; (this.data.filteredList || []).forEach(function (u) { rows.push([u.student_no || u.student_id || '', u.real_name || u.realName || u.name || '', u.card_no || '', u.phone || '', u.college || '', u.major || '', u.grade || '', u.class_name || u.className || '', u.building_id || u.buildingId || '', u.room_number || u.roomNumber || '', u.credit_score || '', u.status || '']) }); writeAndOpenExcel('宿生名单导出.xls', rows) },
  onAdjustCredit: function (e) { var that = this; var id = e.currentTarget.dataset.id; var currentScore = e.currentTarget.dataset.score; wx.showModal({ title: '调整信用分', content: '当前信用分: ' + currentScore, editable: true, placeholderText: '输入新的信用分(0-100)', success: function (res) { if (res.confirm) { var newScore = parseInt(res.content); if (isNaN(newScore) || newScore < 0 || newScore > 100) { wx.showToast({ title: '请输入0-100的数字', icon: 'none' }); return } request.put('/credit/adjust', { userId: id, score: newScore }).then(function () { wx.showToast({ title: '已调整', icon: 'success' }); that.loadData() }).catch(function () { wx.showToast({ title: '调整失败', icon: 'none' }) }) } } }) },
  onToggleBan: function (e) { var that = this; var id = e.currentTarget.dataset.id; var status = e.currentTarget.dataset.status; var action = status === 'banned' ? '解封' : '封禁'; wx.showModal({ title: '确认' + action, content: '确定要' + action + '该宿生？', success: function (res) { if (res.confirm) { var newStatus = status === 'banned' ? 'active' : 'banned'; request.put('/user/list/' + id + '/status', { status: newStatus }).then(function () { wx.showToast({ title: action + '成功', icon: 'success' }); that.loadData() }).catch(function () { wx.showToast({ title: action + '失败', icon: 'none' }) }) } } }) }
})